#!/bin/bash





init_install() {
    # Curl
    sudo apt install curl 

    # WGet
    sudo apt install wget 
    
    # Git 
    sudo apt install git

    sudo apt update

    add_repositories
    install_packages
}





add_repositories() {
    # Papirus
    sudo add-apt-repository ppa:papirus/papirus

    # asdf
    git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.0
}





install_packages() {
    sudo apt update 

    # Papirus
    sudo apt install papirus-icon-theme

    # Snap
    sudo apt install snapd

    # asdf
    . "$HOME/.asdf/asdf.sh"
    . "$HOME/.asdf/completions/asdf.bash"

    # nodejs
    asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
    asdf install nodejs 21.0.0
    asdf global nodejs 21.0.0
}