#!/bin/bash





init_install() {
    # Curl
    sudo apt install curl 

    # WGet
    sudo apt install wget 
    
    # Git 
    sudo apt install git

    sudo apt update

    add_repositories
    install_packages
}





add_repositories() {
    # Papirus
    sudo add-apt-repository ppa:papirus/papirus
}





install_packages() {
    sudo apt update 

    # Papirus
    sudo apt install papirus-icon-theme
}